### ISSUE TITLE
failed to retreive duration data, reason: No longer available

### ISSUE THREAD

**Issue by flipjs** [mozilla/popcorn-js#461]
I am getting this error "failed to retreive duration data, reason: No longer available". Youtube video used to work. Is there any quick fix for this? Thanks.

**Comment by flipjs** [comment]
Just found the fix: #441 , but I think the pull-request has not been approved yet cause I had to apply the fix manually on 1.5.6 version. Anyways, thanks for this.

**Comment by syl22-00** [comment]
The pull request was merged a while ago, latest version does include the youtube fix.However, only an old version is available on http://popcornjs.org/download, you should probably build it yourself, for example from the latest tag (1.5.11).

**Comment by flipjs** [comment]
I didn't know that. I thought I have the latest version. Thanks for letting me know.

**Comment by steeevio** [comment]
I have the same issue. Sorry if its a silly question but how do I go about building it myself?
