### ISSUE TITLE
The way to replay video ?

### ISSUE THREAD

**Issue by davidanquetin** [mozilla/popcorn-js#469]
Hello

in my project, i have a Popcorn video Instance, without controls option (i make my own control buttons)

when i play for the first time with my PLAY Button, it is ok. The play()/pause() are ok.
When the video is all played once, at the end, i would that the play() function to play the video from the beginning again..
But nothing is happened.. The play() event is emitted, but the video is not played in my view..

I tried to force currentTime after the end of first playing (myPopcornInstance.currentTime(0)), but i does not work..
I tried to force play and pause at time 0 with play(0).pause(0), but does not work...

I think there is a simple way to do this, that i missed , or that i did not understood ?...

Thanks !
David

**Comment by cadecairos** [comment]
Hello @davidanquetin, 

You can try listening for the [ended](http://popcornjs.org/popcorn-docs/events/#ended) event.

```js
var $pop = Popcorn("#video");
$pop.on("ended", function() {
  $pop.currentTime(0);  
});
```
