### ISSUE TITLE
Website forward is broken for popcornjs.org

### ISSUE THREAD

**Issue by kirkins** [mozilla/popcorn-js#476]
Is there an old archive of the website?

The current site forwards to github for example if I search popcornjs on Google I see the result 

> popcornjs.org/download

Which forwards to:

> https://github.com/mozilla/popcorn-js/download

Was the intention to forward to a github.io page?

**Comment by Pomax** [comment]
ping @cadecairos

**Comment by cadecairos** [comment]
Good catch, yeah. Paths need to be stripped.

**Comment by cadecairos** [comment]
OK the redirect has been updated to strip paths from the redirect.
